KTRQ/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
import quiz
from quiz import views


urlpatterns = [
    url(r'^quiz/', include('quiz.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^register/', views.Register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url
from . import views
from .views import *


urlpatterns = (         url(r'^$', 
                            views.home, 
                            name='home'),

                        url(r'profile/$', 
                            views.profile, 
                            name='profile' ),
                        
                        url(r'profile_get/(?P<user_id>\d+)/$', 
                            views.profile_get, 
                            name='profile_get' ),

                        url(r'^rating_list/$', 
                            views.rating_list, 
                            name='rating_list' ),

                        url(r'change_password/$', 
                            views.change_password, 
                            name='change_password'),

                        url(r'rating_category_list/$', 
                            views.rating_category_list, 
                            name='rating_category_list'),

                        url(regex=r'rating_category_list/(?P<cat_id>\d+)/$',
                           view=CategoryRatingDetailView.as_view(),
                           name='rating_category_list'),                            
                        
                        url(r'rating_tests_list/$', 
                            views.rating_tests_list, 
                            name='rating_tests_list'),
                        
                        url(regex=r'rating_tests_list/(?P<quiz_id>\d+)/$',
                           view=QuizRatingDetailView.as_view(),
                           name='rating_ten_lucky'),

                        url(regex=r'rating_list/rating_ten_lucky/$',
                           view=LuckyRatingView.as_view(),
                           name='rating_ten_lucky'),

                        url(regex=r'rating_list/rating_ten_looser/$',
                           view=LooserRatingView.as_view(),
                           name='rating_ten_looser'), 

                        url(regex=r'^list/$',
                           view=QuizListView.as_view(),
                           name='quiz_index'),

                        url(regex=r'^list_pte/$',
                           view=QuizListViewPte.as_view(),
                           name='quiz_index_pte'),

                        url(regex=r'^list_other/$',
                           view=QuizListViewOther.as_view(),
                           name='quiz_index_other'),

                        url(regex=r'^graphs/(?P<cat_name>(.*))/$',
                           view=GraphView.as_view(),
                           name='quiz_graph'),

                        url(regex=r'^category/$',
                           view=CategoriesListView.as_view(),
                           name='quiz_category_list_all'),

                        url(regex=r'^category/(?P<category_name>[\w|\W-]+)/$',
                           view=ViewQuizListByCategory.as_view(),
                           name='quiz_category_list_matching'),

                        url(regex=r'^progress/$',
                           view=QuizUserProgressView.as_view(),
                           name='quiz_progress'),

                        url(regex=r'^marking/$',
                           view=QuizMarkingList.as_view(),
                           name='quiz_marking'),

                        url(regex=r'^marking/(?P<pk>[\d.]+)/$',
                           view=QuizMarkingDetail.as_view(),
                           name='quiz_marking_detail'),

                        #  passes variable 'quiz_name' to quiz_take view
                        url(regex=r'^(?P<slug>[\w-]+)/$',
                           view=QuizDetailView.as_view(),
                           name='quiz_start_page'),

                        url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',
                           view=QuizTake.as_view(),
                           name='quiz_question'),
)

quiz/models.py
import re
import json, datetime
from urllib import request
from django.utils.timezone import now
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import MaxValueValidator
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import redirect
from model_utils.managers import InheritanceManager
from django.core.validators import RegexValidator, validate_comma_separated_integer_list
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Filial(models.Model):
    name = models.CharField(
        verbose_name=("Филиал"),
        max_length=200,
        unique = True,
        null = True,
        blank = True,
    )

    class Meta:
        verbose_name = ("Филиал")
        verbose_name_plural = ("Филиалы")

    def __str__(self):
        return self.name

class Department(models.Model):
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE,
        verbose_name=("Филиал"))
    name = models.CharField(
        verbose_name=("Департамент/Служба/Отдел"),
        max_length=200,
        null = True, 
        blank = True,)

    class Meta:
        verbose_name = ("Департамент/Служба/Отдел")
        verbose_name_plural = ("Департамент/Служба/Отдел")

    def __str__(self):
        return self.name

class Position(models.Model):
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE,
        verbose_name=("Филиал"), 
        related_name='filial_article_set')
    department = models.ForeignKey(Department, on_delete=models.CASCADE,
        verbose_name=("Департамент/Служба/Отдел"), default = 1, 
        related_name='department_article_set',)
    name = models.CharField(
        verbose_name=("Должность"),
        max_length=200,
        unique = True,
        null = True,
        blank = True,)

    class Meta:
        verbose_name = ("Должность")
        verbose_name_plural = ("Должности")

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, default = None,
        null = True,
        on_delete=models.CASCADE)

    avatar = models.ImageField(upload_to = 'profile_images/', default = 'profile_images/no-img.png')

    city = models.CharField(
        verbose_name=("Город/Село"),
        max_length=100,
        unique=True,
        null = True,
        blank = True,
    )

    filial = models.ForeignKey(
        Filial, 
        on_delete=models.CASCADE,
        verbose_name=("Филиал"),
        null=True
    )

    department = models.ForeignKey(Department, on_delete=models.CASCADE,
        verbose_name=("Департамент/Служба/Отдел"), null=True,
    )

    position = models.ForeignKey(Position, on_delete=models.CASCADE,
        verbose_name=("Должность"),
        null=True,
    )

    class Meta:
        verbose_name = ("Личный профиль пользователя")
        verbose_name_plural = ("Личный профиль пользователей")

    def __str__(self):
        return "Профиль пользователя: %s" % self.user

    User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0]) 

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.profile.save()

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()



class CategoryManager(models.Manager):

    def new_category(self, category):
        new_category = self.create(category=re.sub('\s+', '-', category)
                                   .lower())

        new_category.save()
        return new_category


class Category(models.Model):

    category = models.CharField(
        verbose_name=("Категория теста"),
        max_length=250, blank=True,
        unique=True, null=True)

    objects = CategoryManager()

    class Meta:
        verbose_name = ("Категория")
        verbose_name_plural = ("Категории")

    def __str__(self):
        return self.category


class SubCategory(models.Model):

    sub_category = models.CharField(
        verbose_name=("Подкатегория"),
        max_length=250, blank=True, null=True)

    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.CASCADE,
        verbose_name=("Категория"))

    objects = CategoryManager()

    class Meta:
        verbose_name = ("Подкатегория")
        verbose_name_plural = ("Подкатегории")

    def __str__(self):
        return self.sub_category + " (" + self.category.category + ")"



class Quiz(models.Model):

    ATTEMPT_LIST = (
        ('D', 'Одна попытка в день'),
        ('M', 'Одна попытка в месяц'),
        ('Y', 'Одна попытка в год'),
        ('U', 'Неограниченные попытки'),
    )

    title = models.CharField(
        verbose_name=("Название теста"),
        max_length=60, blank=False, help_text=("Введите название теста"))

    description = models.TextField(
        verbose_name=("Описание теста"),
        blank=True, help_text=("Введите описание теста"))

    url = models.SlugField(
        max_length=60, blank=False,
        help_text=("Читаемая url-ссылка для пользователя"),
        verbose_name=("user friendly url"))
    
    filial = models.ForeignKey(
        Filial, null=True, blank=True, default='Все', on_delete=models.CASCADE,
        verbose_name=("Филиал"), help_text=("Выберите филиал, для которого будет доступен тест. Если вы хотите, что бы тест был доступен всем, то оставьте это поле без изменений"))

    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.CASCADE,
        verbose_name=("Категория"), help_text=("Выберите категорию теста"))

    random_order = models.BooleanField(
        blank=False, default=True,
        verbose_name=("Случайная последовательность выдачи вопросов"),
        help_text=("Если да, показывает вопросы в случайной последовательности"))

    max_questions = models.PositiveIntegerField(
        blank=True, null=True, verbose_name=("Максимальное кол-во вопросов"),
        help_text=("Максимальное количество вопросов за одну попытку сдачи теста"))

    answers_at_end = models.BooleanField(
        blank=False, default=False,
        help_text=("Если да, после ответа пользователя на вопрос, будет показан правильный вариант"),
        verbose_name=("Правильный ответ в конце"))

    exam_paper = models.BooleanField(
        blank=False, default=False,
        help_text=("Если да, то результат каждой попытки"
                    " будет сохраняться. Необходимо для маркировки."),
        verbose_name=("Результат теста"))

    single_attempt = models.BooleanField(
        blank=False, default=False,
        help_text=("Если да, то будет разрешена только одна попытка сдачи теста."
                    " Незарегиситрированные пользователи не смогут сдать экзамен."),
        verbose_name=("Одна попытка?"))

    attempt_choise = models.CharField(
        blank=False,
        max_length=50,
        default='U',
        choices=ATTEMPT_LIST
    )

    pass_mark = models.SmallIntegerField(
        blank=True, default=0,
        verbose_name=("Порог прохождения теста"),
        help_text=("Процент необходимый для сдачи теста"),
        validators=[MaxValueValidator(100)])

    success_text = models.TextField(
        blank=True, help_text=("Показывает введенный текст если пользователь сдал тест."),
        verbose_name=("Объявление в случае сдачи теста"))

    fail_text = models.TextField(
        verbose_name=("Объявление в случае провала теста"),
        blank=True, help_text=("Показывает введенный текст если пользователь провалил тест."))

    draft = models.BooleanField(
        blank=True, default=False,
        verbose_name=("В процессе разработки"),
        help_text=("Если да, то тест будет виден только админам."))

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        self.url = re.sub('\s+', '-', self.url).lower()

        self.url = ''.join(letter for letter in self.url if
                           letter.isalnum() or letter == '-')

        if self.single_attempt is True:
            self.exam_paper = True
        
        if self.attempt_choise == 'D':
            self.exam_paper = True
        
        if self.attempt_choise == 'M':
            self.exam_paper = True
        
        if self.attempt_choise == 'Y':
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = ("Тест")
        verbose_name_plural = ("Тесты")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def anon_score_id(self):
        return str(self.id) + "_score"

    def anon_q_list(self):
        return str(self.id) + "_q_list"

    def anon_q_data(self):
        return str(self.id) + "_data"





class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user,
                                   score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    """
    Данный класс используется для записи результата пользователя в разных тестах
    и категориях. Данные сохраняются в csv-формате:
        категория, результат, возможный результат, 
        категория, результат, возможный результат... итд ...
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=("Пользователь"))

    score = models.CharField(validators=[validate_comma_separated_integer_list], max_length=1024, verbose_name=("Результат"))

quiz/forms.py
from django import forms
import json
from django.forms.widgets import RadioSelect, Textarea
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.MultipleChoiceField(choices=choice_list,
                                                   widget=forms.CheckboxSelectMultiple)


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

class ProfileForm(forms.ModelForm):

    dpositions = {}
    list_positions = []
    for position in Position.objects.all():
        if position.department.name in dpositions:
            dpositions[position.department.name].append(position.name)
        else:
            dpositions[position.department.name] = [position.name]
        list_positions.append((position.name,position.name))

    departments = [str(department) for department in Department.objects.all()]

    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    filial = forms.ModelChoiceField(queryset=Filial.objects.all(), empty_label="Пусто", widget=forms.Select(attrs={'class': 'form-control'}))
    department = forms.ChoiceField(choices=([(department, department) for department in departments]), widget=forms.Select(attrs={'class': 'form-control'}))
    position = forms.ChoiceField(choices=(list_positions), widget=forms.Select(attrs={'class': 'form-control'}))
    avatar = forms.ImageField()

    departments = json.dumps(departments)
    positions = json.dumps(dpositions)

    class Meta:
        model = UserProfile
        fields = ('city', 'filial', 'department', 'position', 'avatar',)

quiz/templates/correct_answer.html
{% load i18n %}
{% if previous.answers %}

  {% if user_was_incorrect %}
    <div class="alert alert-error">
  	  <strong>{% trans "Вы неправильно ответили на указанный вопрос" %}</strong>
    </div>
  {% endif %}

  <table class="table table-striped table-bordered">
    <tbody>
  	  {% for answer in previous.answers %}
        {% if answer.correct_or_not.value == "Да" %}
  	    <tr class="success">
  		  <td>{{ answer.answer }}</td>
  		  <td><strong>{% trans "Это правильный ответ" %}</strong></td>
        {% else %}
  		<tr>
      	  <td>{{ answer.answer }}</td>
  		    <td>
  			  {% if previous.question_type.MCQuestion %}
  			    {% if answer.id|add:"0" == previous.previous_answer|add:"0" %}
  			      {% trans "Это был ваш ответ." %}
  			    {% endif %}
  			  {% endif %}
  		  </td>
  	    {% endif %}
  	  </tr>
  	{% endfor %}
    </tbody>
  </table>
{% endif %}

quiz/templates/graphs.html
{% extends "base.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}

{% block content %}

{{ category }}

<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<div id="container" style="margin-top: 20%"></div>
<script>
    $(function () {
        var chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                backgroundColor: {
                    linearGradient: { x1: 0, y1: 0, x2: 1, y2: 1 },
                    stops: [
                        [0, 'rgb(255, 255, 255)'],
                        [1, 'rgb(200, 200, 255)']
                    ]
                },
                type: 'line'
            },
            title: {
                text: 'График вашей результативности по сдаче теста'
            },
            xAxis: {
                categories: [{% for exam in exams %} {% if exam.quiz.category == category %} "{{ exam.end|date:"Y-m-d" }}" {% if not forloop.last %}, {% endif %} {% endif %} {% endfor %}]
            },
            yAxis: {
                title: {
                    text: 'Результат (%)'},
                max: 100
            },
            legend: {
                    layout: 'vertical',
                    backgroundColor: '#FFFFFF',
                    floating: true,
                    align: 'left',
                    x: 70,
                    verticalAlign: 'top',
                    y: 5
                },
            tooltip: {
                formatter: function() {
                    return '<b>'+ this.series.name +'</b><br/>'+
                        this.x +': '+ this.y;
                }
            },
            plotOptions: {
            },
            series: [{
                name: 'Результат',
                data: [{% for exam in exams %} {% if exam.quiz.category == category %} {{ exam.get_percent_correct }}{% if not forloop.last %}, {% endif %} {% endif %} {% endfor %}],
                color: 'cornflowerblue'
            }]
        });
    });
</script>
</div>

{% endblock %}

quiz/templates/home.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% trans "KTRQ" %} | {% trans "Домашняя" %}</title>

	    <!-- css -->
		<link rel="stylesheet" href="/static/quiz/css/bootstrap.min.css">
		<link rel="stylesheet" href="/static/quiz/css/custom.css">
		<!-- css -->

	</head>

	<body>
		<div id="wrapper">
			<div id="overlay-1">
				
				<!-- header section -->
				<section id= "navigation">
					<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  					<div class="container-fluid">
	    					<div class="navbar-header">
	      						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					        		<span class="ion-navicon"></span>
					      		</button>
					      		<a class="navbar-brand" href="/quiz">KTRQ</a>
					    	</div>
	    					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      					<ul class="nav navbar-nav navbar-right">
		      						<li><a href="/quiz/">Домашняя</a></li>
		        					<li><a href="/quiz/profile/">Профиль</a></li>
		        					<li><a href="/quiz/rating_list/">Рейтинги</a></li>
                      				<li><a href="/quiz/suggest/">Предложения</a></li>
									{% if request.user.is_superuser %}
										<li><a href="/quiz/marking/">Результаты</a></li>
									{% endif %}
		        					<li><a href='/accounts/logout' class="btn btn-primary">Выйти</a></li>
							    </ul>
	    					</div>
	  					</div>
					</nav>
				</section>
				<!-- header section -->
				
				<!-- central section -->
				<section id="starting">
					<div class="text-center starting-text">
						<h1 class="rene">KTRQ</h1>
						<h2>Добро пожаловать {{ user.first_name }}! 
							Вы вошли в систему тестирования. 
              				Здесь вы можете протестироваться и проверить свои знания. 
            			</h2>
						<a style='font-size: 25px;' class='btn btn-logout' href="/quiz/list">
							Перейти к тестам
						</a>
					</div>
				</section>
				<!-- central section -->

				<div id="bottom" class="bottom text-center">
			        <a href="#about"><i class="ion-ios7-arrow-down"></i></a>
				</div>
				
			</div>
		</div>		
			
		<!-- footer -->
		<section id= "footer" class= "main-footer">
			<div class= "row">
				<div class= "copyright text-center">
					<p> © 2019 KTRQ. Разработал Окасов Марат</p>
					<p>ДНСТ АО "Казтелерадио"</p>
				</div>
			</div>
		</section>
		<!-- footer -->

	</body>
</html>

quiz/templates/profile_get.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% load quiz_tags %}

{% block title %} {{ quiz.title}} {% endblock %}
{% block description %} {% trans "Результаты теста:" %} {{ quiz.title }} {% endblock %}

{% block content %}


    <div class="container">
        <div class="row m-y-2">
            <div class="col-lg-8 push-lg-4">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Профиль пользователя</a>
                    </li>
                </ul>
                <div class="tab-content p-b-3">
                    <div class="tab-pane active" id="profile">
                        <p><h4 class="m-y-2">{{ user_form.first_name }} {{ user_form.last_name }}</h4></p>
                        <p><h5 class="m-y-2">Email: {{ user_form.email }}</h5></p>
                        <div class="row">
                            <div class="col-md-6">
                                <h6>Город проживания</h6>
                                <p class="font-italic">
                                    {{ user_form.userprofile.city }}
                                </p>
                                <h6>Филиал</h6>
                                <p class="font-italic">
                                    {{ user_form.userprofile.filial }}
                                </p>
                                <h6>Департамент/Служба/Отдел</h6>
                                <p class="font-italic">
                                    {{ user_form.userprofile.department }}
                                </p>
                                <h6>Должность</h6>
                                <p class="font-italic">
                                    {{ user_form.userprofile.position }}
                                </p>
                                <h6>Hobbies</h6>
                                <p>
                                    Indie music, skiing and hiking. I love the great outdoors.
                                </p>
                            </div>
            <div class="col-lg-3 pull-lg-8 text-xs-center">
                <img src="{{ user_form.userprofile.avatar.url }}" class="rounded-circle" width='200' height="200" alt="avatar">
            </div>
{% endblock %}

quiz/templates/progress.html
{% extends "base.html" %} 
{% load i18n %} 
{% load quiz_tags %} 
{% block title %} 
    {% trans "Страница прогресса" %} 
{% endblock %} 

{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<div style="padding: 3%">
    {% if cat_scores %}

    <h1>{% trans "Общие результаты тестов по категориям" %}</h1>
    <hr>
    <table id='cat_table_id'>
        <thead>
            <tr class="table100-head">
                <th>{% trans "Категория" %}</th>
                <th>{% trans "Правильные" %}</th>
                <th>{% trans "Неправильные" %}</th>
                <th>{% trans "В процентах (%)" %}</th>
                <th>{% trans "График" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for cat, value in cat_scores.items %}
            <tr>
                <td>{{ cat }}</td>
                <td>{{ value.0 }}</td>
                <td>{{ value.1 }}</td>
                <td>{{ value.2 }}</td>
                <td><a href="/quiz/graphs/{{ cat }}">График</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %} {% if exams %}

    <hr>

    <h1>{% trans "Результаты тестов" %}</h1>
    <p class="lead">
        {% trans "Ниже приведены результаты тестов, которые вы сдавали." %}
    </p>
    <hr>
    <table id='result_table_id'>
        <thead>
            <tr class="table100-head">
                <th>{% trans "Название теста" %}</th>
                <th>{% trans "Дата сдачи" %}</th>
                <th>{% trans "Баллы" %}</th>
                <th>{% trans "Максимальный балл" %}</th>
                <th>{% trans "В процентах (%)" %}</th>
                <th>{% trans "Результат" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for exam in exams %}
            <tr>
                <td>{{ exam.quiz.title }}</td>
                {% language 'ru' %}
                <td>{{ exam.end }}</td>
                {% endlanguage %}
                <td>{{ exam.current_score }}</td>
                <td>{{ exam.get_max_score }}</td>
                <td>{{ exam.get_percent_correct }}{% trans "%" %}</td>
                {% if exam.get_percent_correct >= exam.quiz.pass_mark %}
                <td class="td-success">{% trans "Сдал" %}</td>
                {% else %}
                <td class="td-failure">{% trans "Провалил" %}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <script language="javascript">
        $(document).ready(function() {
            $('#result_table_id').DataTable();
        });
    </script>
    <script language="javascript">
        $(document).ready(function() {
            $('#cat_table_id').DataTable();
        });
    </script>
    {% endif %}
</div>
{% endblock %}

quiz/templates/rating_tests_list.html
{% extends "base.html" %} 
{% load i18n %} 
{% load quiz_tags %} 

{% block title %} 
    {% trans "Рейтинг по тестам" %} 
{% endblock %} 

{% block content %}

<!-- css datatables -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<!-- css datatables -->

<!-- js datatables -->
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<!-- js datatables -->

<div style="padding: 3%">
    <div class="row text-center" id="heading">
         <div class="col-md-6 col-md-offset-3 wow animated zoomInDown" id="heading-text">
            <h3>Рейтинг по отдельным тестам</h3>
                <p>Здесь вы можете увидеть рейтинг пользователей с наилучшими показателями сдал/провалил
                        по каждому тесту в отдельности.
                </p>
                <hr>
        </div>
    </div> 
    {% if quiz_list %}
    <table id='quiz_table_id'>

        <thead>
            <tr class="table100-head">
                <th>{% trans "Тест" %}</th>
                <th>{% trans "Рейтинг" %}</th>
            </tr>
        </thead>

        <tbody>
            {% for quiz in quiz_list %}
            <tr>
                <td>{{ quiz }}</td>
                <td><a href='rating_tests_list/{{ quiz.id }}'>Рейтинг</a></td>
            </tr>
            {% endfor %}
        </tbody>
    
    </table>

    {% endif %}
    
</div>

<!-- js datatables -->
<script language="javascript">
    $(document).ready(function() {
        $('#quiz_table_id').DataTable();
    });
</script>
<!-- js datatables -->

{% endblock %}